fast: true
model: yolov8n.pt
data: dataset/data.yaml
epochs: 30
imgsz: 512
batch: 16
optimizer: AdamW
lr0: 0.001
augment: true
hsv_h: 0.01
hsv_s: 0.5
hsv_v: 0.3
degrees: 0.0
translate: 0.05
scale: 0.3
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
blur: 0.15
mosaic: 0.5
mixup: 0.0
copy_paste: 0.1
conf: 0.25
iou: 0.5

